# Script to load libraries
suppressWarnings(suppressMessages(library(metagenomeSeq)))
suppressWarnings(suppressMessages(library(vegan)))
suppressWarnings(suppressMessages(library(ggplot2)))
suppressWarnings(suppressMessages(library(tidyverse)))
suppressWarnings(suppressMessages(library(phyloseq)))
suppressWarnings(suppressMessages(library(data.table)))
suppressWarnings(suppressMessages(library(gridExtra)))
suppressWarnings(suppressMessages(library(geometry)))
suppressWarnings(suppressMessages(library(rgl)))
suppressWarnings(suppressMessages(library(scales)))
suppressWarnings(suppressMessages(library(gplots)))
suppressWarnings(suppressMessages(library(ggrepel)))
suppressWarnings(suppressMessages(library(RColorBrewer)))
suppressWarnings(suppressMessages(library(ggthemes)))

# Optional tools for 3D figures
#library(rtools)
#library(plotly)
#library(plot3D)
#library(gg3D) # https://github.com/AckerDWM/gg3D, library(devtools) , install_github("https://github.com/AckerDWM/gg3D")
#library(ggbiplot) #  install_github("vqv/ggbiplot")
#library(magick)
